### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by markimpmc** [rubenspgcavalcante/leaflet-ant-path-bower#1]
Rubens,

está faltando os css e css.map na pasta dist.

O nome do pacote também está leaflet-ant-path no bower.json e documentação.

Abraços.

**Comment by rubenspgcavalcante** [comment]
Olá marcos,
Esse repositório foi criado para separar do package npm que faz o build na hora da instalação. Como o bower não faz isso, foi me recomendado pelos criadores do Leaflet essa separação.
Ah, nessa versão eu estou fazendo o bundle da aplicação utilizando o webpack, que já injeta dentro do arquivo final o estilo.

Eu mantive o nome do pacote como leaflet-ant-path por ele ser referente ainda ao código do repositório oficial, inclusive ainda sendo instalado via 'bower install leaflet-ant-path'.
